import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { CTA } from "@/components/Sections";
import { JsonLd, breadcrumbSchema } from "@/components/JsonLd";
import { industries } from "@/lib/site-data";

export function generateStaticParams(){return industries.map((i)=>({slug:i.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const i=industries.find((x)=>x.slug===slug);if(!i)return{};const url=`https://seara.id/industri/${i.slug}`;return{title:i.seoTitle,description:i.seoDescription,alternates:{canonical:url},openGraph:{title:i.seoTitle,description:i.seoDescription,url,type:"website"}};}
export default async function IndustryDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const i=industries.find((x)=>x.slug===slug);if(!i)notFound();const url=`https://seara.id/industri/${i.slug}`;const schema={"@context":"https://schema.org","@type":"WebPage","@id":`${url}#webpage`,url,name:i.seoTitle,description:i.seoDescription,inLanguage:"id-ID",publisher:{"@id":"https://seara.id/#organization"},isPartOf:{"@id":"https://seara.id/#website"}};return <><JsonLd data={[schema,breadcrumbSchema([{name:"Beranda",url:"https://seara.id"},{name:"Industri",url:"https://seara.id/industri"},{name:i.title,url}])]}/><Header/><main><div className="wrap heroSingle"><span className="eyebrow">SOLUSI INDUSTRI</span><h1>{i.title}: <span className="gradient">operasional yang lebih terhubung.</span></h1><p className="lead">{i.description}</p><div className="heroActions"><Link className="btn btnBlue" href="/contact">Coba Demo →</Link><Link className="btn btnGhost" href="/industri">Industri Lainnya</Link></div></div><section><div className="wrap compare"><div className="compareCol old"><h3>Tantangan yang sering terjadi</h3><ul>{i.problems.map((x)=><li key={x}>{x}</li>)}</ul></div><div className="compareCol new"><h3>Workflow dengan Seara</h3><ul>{i.solutions.map((x)=><li key={x}>{x}</li>)}</ul></div></div></section><section><div className="wrap faqSection"><details><summary>Produk Seara apa yang relevan untuk {i.title}?</summary><p>Kombinasi produk tergantung workflow. CRM cocok untuk customer dan lead operations, sementara HR, Finance, Retail/POS, atau Manufacturing dapat ditambahkan sesuai kebutuhan.</p></details><details><summary>Apakah bisa digunakan untuk multi-unit atau cabang?</summary><p>Kebutuhan multi-unit dapat dipetakan dalam implementasi. Seara CRM secara khusus mendukung struktur multi-unit dan multi-tenant.</p></details><details><summary>Bagaimana memulai implementasi?</summary><p>Jadwalkan demo agar tim Seara dapat memahami proses saat ini dan menentukan modul serta workflow yang paling relevan.</p></details></div></section><CTA/></main><Footer/></>}
