import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { JsonLd, breadcrumbSchema } from "@/components/JsonLd";
import { resources } from "@/lib/site-data";

export function generateStaticParams(){return resources.map((r)=>({slug:r.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const r=resources.find((x)=>x.slug===slug);if(!r)return{};const url=`https://seara.id/resources/${r.slug}`;return{title:r.seoTitle,description:r.seoDescription,alternates:{canonical:url},openGraph:{title:r.seoTitle,description:r.seoDescription,url,type:"website"}};}
export default async function ResourceDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const r=resources.find((x)=>x.slug===slug);if(!r)notFound();const url=`https://seara.id/resources/${r.slug}`;const schema={"@context":"https://schema.org","@type":"CollectionPage","@id":`${url}#webpage`,url,name:r.seoTitle,description:r.seoDescription,inLanguage:"id-ID",publisher:{"@id":"https://seara.id/#organization"},isPartOf:{"@id":"https://seara.id/#website"}};return <><JsonLd data={[schema,breadcrumbSchema([{name:"Beranda",url:"https://seara.id"},{name:"Resource",url:"https://seara.id/resources"},{name:r.title,url}])]}/><Header/><main><div className="wrap heroSingle"><span className="eyebrow">{r.title.toUpperCase()}</span><h1>{r.title} untuk <span className="gradient">operasional yang lebih baik.</span></h1><p className="lead">{r.description}</p></div><section><div className="wrap"><div className="sectionHead"><h2>Topik utama.</h2><p>Struktur halaman ini siap dihubungkan ke CMS ketika konten editorial Seara mulai dipublikasikan.</p></div><div className="capabilityGrid">{r.topics.map((t)=><span key={t}>{t}</span>)}</div><div className="resourceEmptyState"><h3>Gunakan {r.title} sesuai kebutuhan tim.</h3><p>Halaman ini menjadi pusat materi {r.title.toLowerCase()} Seara. Gunakan topik di atas untuk menentukan materi yang paling relevan dengan workflow Anda.</p><div className="heroActions"><Link className="btn btnBlue" href="/contact">Tanya Tim Seara →</Link><Link className="btn btnGhost" href="/resources">Resource Lainnya</Link></div></div></div></section></main><Footer/></>}
